# Generated by Django 4.2.1 on 2023-07-02 23:13

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('IDAdmin', models.AutoField(primary_key=True, serialize=False)),
                ('NombreAdm', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('IDCate', models.AutoField(primary_key=True, serialize=False)),
                ('NombreCate', models.CharField(max_length=50)),
                ('Foto', models.ImageField(null=True, upload_to='fotos')),
            ],
        ),
        migrations.CreateModel(
            name='Mercaderia',
            fields=[
                ('IDMerca', models.AutoField(primary_key=True, serialize=False)),
                ('NombreMerca', models.CharField(max_length=40)),
                ('CodigoBarra', models.IntegerField()),
                ('PrecioVenta', models.IntegerField(default=1000)),
                ('CantidadStock', models.IntegerField()),
                ('descripcion', models.CharField(max_length=300)),
                ('imagen', models.ImageField(default='mercaderias/default', null=True, upload_to='mercaderias')),
            ],
        ),
        migrations.CreateModel(
            name='Periodista',
            fields=[
                ('IDPer', models.AutoField(primary_key=True, serialize=False)),
                ('NombrePer', models.CharField(max_length=50)),
                ('ApellidoPer', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('IDUsuario', models.AutoField(primary_key=True, serialize=False)),
                ('NombreUsu', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('IDNot', models.AutoField(primary_key=True, serialize=False)),
                ('Titulo', models.CharField(max_length=100)),
                ('Descrip', models.TextField(max_length=1000)),
                ('Fecha', models.DateField(verbose_name=datetime.date(2023, 7, 2))),
                ('Foto', models.ImageField(null=True, upload_to='fotos')),
                ('Publicado', models.BooleanField(default=False)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webCaos.categoria')),
                ('periodista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webCaos.periodista')),
            ],
        ),
        migrations.CreateModel(
            name='Galeria',
            fields=[
                ('IDFoto', models.AutoField(primary_key=True, serialize=False)),
                ('Foto', models.ImageField(null=True, upload_to='galeria')),
                ('Noticia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webCaos.noticia')),
            ],
        ),
    ]
