# Generated by Django 4.2.1 on 2023-05-22 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('IDAdmin', models.IntegerField(primary_key=True, serialize=False)),
                ('NombreAdm', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('IDCate', models.IntegerField(primary_key=True, serialize=False)),
                ('NombreCate', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Periodista',
            fields=[
                ('IDPer', models.IntegerField(primary_key=True, serialize=False)),
                ('NombrePer', models.CharField(max_length=50)),
                ('ApellidoPer', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('IDUsuario', models.IntegerField(primary_key=True, serialize=False)),
                ('NombreUsu', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('IDNot', models.IntegerField(primary_key=True, serialize=False)),
                ('TituloNot', models.CharField(max_length=50)),
                ('DescripNot', models.TextField()),
                ('FechaNot', models.DateField()),
                ('Foto', models.ImageField(null=True, upload_to='fotos')),
                ('Categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webCaos.categoria')),
                ('Periodista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webCaos.periodista')),
            ],
        ),
    ]
