# Generated by Django 5.2.5 on 2025-08-07 00:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webCaos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='Fecha',
            field=models.DateField(verbose_name=datetime.date(2025, 8, 6)),
        ),
    ]
