# Generated by Django 4.2.1 on 2023-05-22 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webCaos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='Publicado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='administrador',
            name='IDAdmin',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='IDCate',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='IDNot',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='periodista',
            name='IDPer',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='IDUsuario',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Galeria',
            fields=[
                ('IDFoto', models.AutoField(primary_key=True, serialize=False)),
                ('Foto', models.ImageField(null=True, upload_to='galeria')),
                ('Noticia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webCaos.noticia')),
            ],
        ),
    ]
