# Generated by Django 4.2.1 on 2023-05-22 08:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webCaos', '0002_noticia_publicado_alter_administrador_idadmin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='DescripNot',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='FechaNot',
            field=models.DateField(verbose_name=datetime.date(2023, 5, 22)),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='TituloNot',
            field=models.CharField(max_length=100),
        ),
    ]
