# Generated by Django 4.2.1 on 2023-05-26 03:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webCaos', '0003_alter_noticia_descripnot_alter_noticia_fechanot_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noticia',
            old_name='Categoria',
            new_name='categoria',
        ),
        migrations.RenameField(
            model_name='noticia',
            old_name='Periodista',
            new_name='periodista',
        ),
        migrations.AlterField(
            model_name='noticia',
            name='FechaNot',
            field=models.DateField(verbose_name=datetime.date(2023, 5, 25)),
        ),
    ]
