# Generated by Django 4.2.1 on 2023-05-26 04:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webCaos', '0004_rename_categoria_noticia_categoria_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noticia',
            old_name='DescripNot',
            new_name='Descrip',
        ),
        migrations.RenameField(
            model_name='noticia',
            old_name='TituloNot',
            new_name='Titulo',
        ),
        migrations.AlterField(
            model_name='noticia',
            name='FechaNot',
            field=models.DateField(verbose_name=datetime.date(2023, 5, 26)),
        ),
    ]
