# Generated by Django 4.2.1 on 2023-05-26 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webCaos', '0005_rename_descripnot_noticia_descrip_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noticia',
            old_name='FechaNot',
            new_name='Fecha',
        ),
    ]
