# Generated by Django 4.2.1 on 2023-06-08 00:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webCaos', '0006_rename_fechanot_noticia_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='Foto',
            field=models.ImageField(null=True, upload_to='fotos'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='Fecha',
            field=models.DateField(verbose_name=datetime.date(2023, 6, 7)),
        ),
    ]
